apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-examples
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-examples
    app.kubernetes.io/part-of: integration-examples
  name: integration-examples
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jvm-build-test-project
      app.kubernetes.io/instance: integration-examples
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jvm-build-test-project
        app.kubernetes.io/instance: integration-examples
    spec:
      containers:
      - image: jvm-build-test-project:latest
        name: jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
